# Site settings
title: /r/sigma recommendations
description: >
  A list of recommendations made in the /r/sigma chat room.
baseurl: ""
url: "http://r-sigma.github.io/recommendations/"
github_username:  r-sigma

# GitHub default settings (can't be overridden)
safe: true
lsi: false

# Build settings
markdown: kramdown
exclude: [vendor]
